### PR TITLE
Update react-integration.asciidoc

### PR DESCRIPTION
**Pull request by baruchiro**

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@baruchiro Thanks for the PR, could you sign the CLA.

**Comment by baruchiro** [comment]
I signed, I think. Do I need to upload the document here?

**Comment by vigneshshanmugam** [comment]
@baruchiro Can you rebase this PR. Thanks!

**Comment by baruchiro** [comment]
@vigneshshanmugam Updated

**Review by vigneshshanmugam — APPROVED** [review]
Thanks

**Pull request merged**
