### PR TITLE
chore: always use the same sauce labs config

### PR DESCRIPTION
**Pull request by graphaelli**

### CODE REVIEW

**Comment by devcorpio** [comment]
Hi @graphaelli ,

Do you know the status of this PR? Is this change something that we want still to do?

**Comment by graphaelli** [comment]
@vigneshshanmugam can you weigh in here?  My understanding is that this isn't used at all.

**Comment by vigneshshanmugam** [comment]
Yes, we dont use the `SAUCELABS_SECRET_CORE` token for running the tests. We can remove them. 

Need to change the PR message for the lint to pass through. We can fix that.

**Comment by vigneshshanmugam** [comment]
@devcorpio Need to lint the commit message as well to make it pass the lint check.

**Review by devcorpio — APPROVED** [review]

**Pull request merged**
