### PR TITLE
docs: Update APM guide links to Observability guide links (#1528)

### PR DESCRIPTION
**Pull request by colleenmcginnis**
Backports https://github.com/elastic/apm-agent-rum-js/pull/1528 to 5.x

### CODE REVIEW

**Review by david-luna — APPROVED** [review]

**Comment by colleenmcginnis** [comment]
:wave: @david-luna any tips on how to get the final `all` check to pass? The merge button is still disabled for me.

**Comment by bmorelli25** [comment]
It looks like ci has been added as required on all branches but the check is only enabled to run on `main`:

https://github.com/elastic/apm-agent-rum-js/blob/6464a1d312d5ff1e2591ef3b6979ce9171916cf8/.github/workflows/ci.yml#L14

**Comment by v1v** [comment]
I've just updated the branch protection for `5.x`; `all` is no longer needed. As far as I see, `5.x` was not updated to use GitHub actions, but Jenkins and Jenkins is no longer active. Question: Do we expect any code changes in `5.x` or only docs?

**Comment by bmorelli25** [comment]
> Question: Do we expect any code changes in 5.x or only docs?

AFAIK, only docs. Code changes are force pushed at release time to this branch.

**Pull request merged**
