### PR TITLE
[2.x] docs: update moved secret token link

### PR DESCRIPTION
**Pull request by bmorelli25**
For https://github.com/elastic/apm-server/pull/2728. Must be merged at the same time.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Do we need to backport docs changes to previous versions?

**Comment by bmorelli25** [comment]
@vigneshshanmugam In this case yes. We've restructured the APM Server documentation drastically (which we typically don't do) and it caused the destination of the secret token link to move pages. I have to fix the link as far back as it exists in the RUM documentation.

You are correct that typically this wouldn't be needed as I don't move links around that often.

ci/docs failure is expected as https://github.com/elastic/apm-server/pull/2728 hasn't been merged yet.

**Comment by vigneshshanmugam** [comment]
@bmorelli25 Thanks for the detailed info 🙂. Do you want to wait for the serer PR to get merged before merging this change? 

The changes looks good to me.

**Comment by bmorelli25** [comment]
It's a weird one because if I merge any of these without the others, it will break the main doc build. I'm going to wait for ci to be green (except for docs) and merge all 5 PRs at the same time.

**Comment by vigneshshanmugam** [comment]
Haha, you need a merge bot now 😄

**Pull request merged**
