### PR TITLE
feat(rum-angular)!: support angular ivy

### PR DESCRIPTION
**Pull request by devcorpio**
Related to https://github.com/elastic/apm-agent-rum-js/issues/1345

# Summary

The changes in this PR will make it possible to use Angular RUM integration in Angular **Ivy** Applications, including Angular 16.

E2E tests work properly in each of the browsers we support.

**Angular 16 app using RUM agent WITHOUT the changes**

angular-16-before-change

**Angular 16 app using RUM agent WITH the changes**

angular-16-after-change

--
**The new changes are only compatible with Angular >=12.**

**Note**: From Angular 12 is not possible to disable Ivy

See below the behaviour with older versions:

Angular 9 output:
angular-9

Angular 10 output

angular-10

Angular 11 output
angular-11

## How to test

Bear in mind that there are other ways to test this, but this is my favourite way (closer to the reality, users install packages):

1. Checkout the PR's branch
2. Install [Verdaccio](https://verdaccio.org/docs/installation/) and start it (make sure you are [authenticated](https://verdaccio.org/docs/setup-npm#creating-user/))
3. Publish rum agent in Verdaccio
      - Change the registry value from [lerna.json file](https://github.com/elastic/apm-agent-rum-js/blob/main/lerna.json#L6) to  http://localhost:4873
      - add ```"angular_ivy_support"```in the [allowBranch](https://github.com/elastic/apm-agent-rum-js/blob/main/lerna.json#L9) property
      - execute ```npx lerna publish --no-git-tag-version --no-push```
4. You can confirm that everything has been published by going to http//localhost:4873
5. In your angular app install the RUM angular package: ```npm install @elastic/apm-rum-angular@latest --registry http://localhost:4873```

### CODE REVIEW

**Review by vigneshshanmugam — COMMENTED** [review]
Alberto and myself had a chat offline, we will update the E2E to angular 16 to make it easier for users to reference our example.

**Comment by sergey-tihon** [comment]
May we expect some alpha npm package any time soon to test Ivy support?

**Comment by devcorpio** [comment]
> Alberto and myself had a chat offline, we will update the E2E to angular 16 to make it easier for users to reference our example.

We had a follow-up, we will not do this, the reasons:

- Angular > 12 drop support for IE11 (which wasn't particularly a problem, this wasn't the blocker)
- Angular 16 doesn't support Node.js 14 - which is the version we use in the agent, so we needed to upgrade to Node.js 16
- Update to Node.js implies supporting NPM 7, which opens a new can of worms

That's why it was decided to do this in a separate tech debt issue, now it's the right time to do this update

**Comment by devcorpio** [comment]
@sergey-tihon, I added a "how to test" section in the PR's description

**Review by vigneshshanmugam — APPROVED** [review]
LGTM 🎉 , Tested with Angular 16 and works as expected.

**Pull request merged**
