### PR TITLE
ci: collect JUnit results

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

All a post step to all stages that run unit tests.

## Why is it important?

Fix a bug introduced on https://github.com/elastic/apm-agent-rum-js/pull/542

## Related issues
Closes https://github.com/elastic/apm-agent-rum-js/issues/672

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@kuisathaverat still the test report is not working as expected

**Comment by kuisathaverat** [comment]
@vigneshshanmugam What is missed? I see results from every stack+scope test for puppeteer and SauceLabs 

Screenshot 2020-03-03 at 11 36 58

Screenshot 2020-03-03 at 11 38 53


https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-673/1/tests

**Comment by vigneshshanmugam** [comment]
@kuisathaverat This never completes

Screenshot 2020-03-03 at 13 50 59

**Comment by kuisathaverat** [comment]
I dunno were this check comes from,  there is no `withGithubNotify` step with that name, I'll find the source.

**Comment by kuisathaverat** [comment]
it is a `Require status checks to pass before merging` setting this stage no longer exists, I've made `apm-ci/pr-merge` required

**Pull request merged**
