### PR TITLE
docs: add link to dot net repo 

### PR DESCRIPTION
**Pull request by bmorelli25**
Please wait to merge until after https://github.com/elastic/apm-agent-dotnet/pull/771 has been merged.

The doc build will need to be retried with `@elasticmachine, run elasticsearch-ci/docs`.

### CODE REVIEW

**Comment by bmorelli25** [comment]
Hmmm @vigneshshanmugam , the commit is prefixed with `docs:`

**Comment by bmorelli25** [comment]
I don't know why this isn't working

**Comment by vigneshshanmugam** [comment]
jenkins run the tests please

**Comment by vigneshshanmugam** [comment]
jenkins run the tests please

**Pull request merged**
